version: "3.9"
services:
  rails_dynamodb_db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  rails_dynamodb_web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      AWS_ACCESS_KEY_ID: dynamodb
      AWS_SECRET_ACCESS_KEY: dynamodb
      AWS_DEFAULT_REGION: ap-northeast-1
    depends_on:
      - rails_dynamodb_db
      - rails_dynamodb
  rails_dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: dynamodb
      AWS_SECRET_ACCESS_KEY: dynamodb
      DEFAULT_REGION: ap-northeast-1
  rails_dynamodb-admin:
    container_name: rails_dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=rails_dynamodb:8000
      - AWS_ACCESS_KEY_ID=dynamodb
      - AWS_SECRET_ACCESS_KEY=dynamodb
      - AWS_REGION=ap-northeast-1
    ports:
      - "8001:8001"
    depends_on:
      - rails_dynamodb